name: Deploy to ECR

on:
   push:
    branches: 
     - main
     
jobs:
  buildAndDeployGateway:
    runs-on: ubuntu-latest
    environment: "Prod Env Variables"
    env:
      ECR_REGISTRY: 704975185841.dkr.ecr.us-west-2.amazonaws.com/mobilegreaser
      ECR_REPOSITORY: web-app
      IMAGE_TAG: latest
      PUBLIC_SUPABASE_URL: ${{vars.PUBLIC_SUPABASE_URL}}
    name: Build Image
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - run: echo "PUBLIC_SUPABASE_URL $PUBLIC_SUPABASE_URL"
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      run: |
        aws ecr get-login-password --region us-west-1 | docker login --username AWS --password-stdin 704975185841.dkr.ecr.us-west-1.amazonaws.com
        docker build --build-arg API_GATEWAY_URL=${{vars.API_GATEWAY_URL}} --build-arg PUBLIC_SUPABASE_URL=$PUBLIC_SUPABASE_URL --build-arg PUBLIC_SUPABASE_KEY=${{vars.PUBLIC_SUPABASE_KEY}} --build-arg PUBLIC_POSTHOG_API_KEY=${{vars.PUBLIC_POSTHOG_API_KEY}} --build-arg PUBLIC_POSTHOG_HOST=${{vars.PUBLIC_POSTHOG_HOST}} -t web_app .
        docker tag web_app:latest ${{env.ECR_REGISTRY}}/${{env.ECR_REPOSITORY}}:${{env.IMAGE_TAG}}
        docker push ${{env.ECR_REGISTRY}}/${{env.ECR_REPOSITORY}}:${{env.IMAGE_TAG}}
